default:
  port: 3000
  mongodb_uri: "mongodb://localhost/myapp"
  sessions_secret: "unicorns"

development:
  port: 3000
  mongodb_uri: "mongodb://localhost/myapp"
  sessions_secret: "unicorns"

test:
  port: 3000
  mongodb_uri: "mongodb://localhost/myapp"
  sessions_secret: "unicorns"

production:
  port: 3000
  mongodb_uri: "mongodb://localhost/myapp"
  sessions_secret: "unicorns"